define(function() {
  var soLink = 'https://api.stackexchange.com/2.2/tags?pagesize=1&order=desc&sort=popular&inname=hoodie&site=stackoverflow';
  return [
    ['tech-trigger', 'Hood.ie', 'http://hood.ie/', 'https://github.com/hoodiehq/hoodie.js'],
    ['tech-trigger', 'Koa', 'http://koajs.com/', 'https://github.com/koajs/koa'],
    ['tech-trigger', 'Meteor', 'http://meteor.com/', 'https://github.com/meteor/meteor'],
    ['tech-trigger', 'Derby.js', 'http://derbyjs.com/', 'https://github.com/derbyjs/derby'],
    ['inflated-expectations', 'ReactJS-Flux', 'https://facebook.github.io/flux/', 'http://github.com/facebook/flux'],
    ['inflated-expectations', 'ReactJS', 'https://facebook.github.io/react/', 'https://github.com/facebook/react'],
    ['inflated-expectations', 'Ninja', 'http://www.ninjaframework.org/', 'https://github.com/ninjaframework/ninja'],
    ['inflated-expectations', 'Spring Boot', 'http://projects.spring.io/spring-boot/', 'http://github.com/spring-projects/spring-boot'],
    ['inflated-expectations', 'FOAM', 'http://foam-framework.github.io/foam/', 'https://github.com/foam-framework/foam'],
    ['inflated-expectations', 'Aurelia', 'http://aurelia.io/', 'https://github.com/aurelia/framework'],
    ['inflated-expectations', 'Hapi', 'http://hapijs.com/', 'https://github.com/hapijs/hapi'],
    ['inflated-expectations', 'Mithril', 'https://lhorie.github.io/mithril/', 'http://github.com/lhorie/mithril.js'],
    ['inflated-expectations', 'DropWizard', 'http://www.dropwizard.io/', 'https://github.com/dropwizard/dropwizard'],
    ['disillusionment-trough', 'ExpressJS', 'http://expressjs.com/', 'https://github.com/strongloop/express'],
    ['disillusionment-trough', 'Wicket', 'http://wicket.apache.org/', 'https://github.com/apache/wicket'],
    ['disillusionment-trough', 'Jboss Seam', 'http://seamframework.org/', 'https://github.com/seam/parent'],
    ['enlightenment-slope', 'Stripes', 'https://stripesframework.atlassian.net/wiki/display/STRIPES/Home', 'https://github.com/StripesFramework/stripes'],
    ['enlightenment-slope', 'Laravel', 'http://laravel.com/', 'https://github.com/laravel/laravel'],
    ['enlightenment-slope', 'KnockoutJS', 'http://knockoutjs.com/', 'https://github.com/knockout/knockout'],
    ['enlightenment-slope', 'FlightJS', 'https://flightjs.github.io/', 'https://github.com/flightjs/flight'],
    ['enlightenment-slope', 'EmberJS', 'http://emberjs.com/', 'https://github.com/emberjs/ember.js'],
    ['enlightenment-slope', 'AngularJS', 'http://angularjs.org/', 'https://github.com/angular/angular.js'],
    ['enlightenment-slope', 'Netty', 'http://netty.io/', 'https://github.com/netty/netty'],
    ['enlightenment-slope', 'Grails', 'http://grails.org/', 'https://github.com/grails/grails-core'],
    ['enlightenment-slope', 'GWT', 'http://www.gwtproject.org/', 'https://github.com/gwtproject/gwt'],
    ['productivity-plateau', 'Play', 'http://playframework.com/', 'https://github.com/playframework/playframework'],
    ['productivity-plateau', 'BackboneJS', 'http://backbonejs.org/', 'https://github.com/jashkenas/backbone'],
    ['productivity-plateau', 'YUI', 'http://yuilibrary.com/', 'https://github.com/yui/yui3'],
    ['productivity-plateau', 'Dojo', 'https://dojotoolkit.org/', 'https://github.com/dojo/dojo'],
    ['productivity-plateau', 'ExtJS', 'http://www.sencha.com/products/extjs/#overview', 'http://www.sencha.com/products/extjs/evaluate/', ''],
    ['productivity-plateau', 'jQuery', 'http://jquery.com/', 'https://github.com/jquery/jquery'],
    ['productivity-plateau', 'Struts', 'http://struts.apache.org/', 'https://github.com/apache/struts'],
    ['productivity-plateau', 'Spring MVC', 'http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html', 'https://github.com/spring-projects/spring-framework'],
    ['productivity-plateau', 'ASP.NET', 'http://www.asp.net/', 'https://github.com/aspnet/Mvc'],
    ['productivity-plateau', 'Django', 'https://www.djangoproject.com/', 'https://github.com/django/django'],
    ['productivity-plateau', 'Rails', 'http://rubyonrails.org/', 'https://github.com/rails/rails']
  ];
});
